config/routes.rb
Wekrut::Application.routes.draw do
  devise_for :views
  devise_for :admins, controllers: {registrations: "admins/registrations", sessions: "admins/sessions"}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", sessions: "users/sessions"}
  resources :users
  resources :admins
  resources :charges
  resources :jobs do
    collection do
      get 'private'
    end
  end

  resources :invitations
  resources :user_profiles

  resources :referrals
  resources :whitelists

  resources :companies do
    member do
      get 'private'
      resources :private_invitations
    end

  end
  resources :accesses

  root "home#index"
  match '/private/:access_token', to: 'home#private', via: 'get'
  match '/send_request', to: 'home#send_request', via: 'post'
  match '/send_company_request', to: 'home#send_company_request', via: 'post'

end

app/views/layouts/shared/_admin_links.html.erb
<li> <%= link_to 'Referral Dashboard', admin_path(current_admin.id) %> </li><li> <%= link_to current_admin.company.name, company_path(current_admin.company.id) %> </li>
<li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>

app/views/layouts/shared/_enterprise_links.html.erb
<li> <%= link_to 'Referral Dashboard', admin_path(current_admin.id) %> </li><li> <%= link_to current_admin.company.name, company_path(current_admin.company.id) %> </li>
<li><%= link_to "Private Settings", private_company_path(current_admin.company.id) %></li>
<li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>

app/views/layouts/shared/_main_admin_links.html.erb
<li> <%= link_to 'Referral Dashboard', admin_path(current_admin.id) %> </li><li> <%= link_to current_admin.company.name, company_path(current_admin.company.id) %> </li>
<li><%= link_to "Private Settings", private_company_path(current_admin.company.id) %></li>
<li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>

app/views/layouts/shared/_user_links.html.erb
<li> <%= link_to 'My Referrals', user_path(current_user.id)%> </li>
<% unless current_user.user_profile.nil? %>
  <li> <%= link_to 'My Profile', user_profile_path(current_user.user_profile.id)%> </li>
<% else %>
  <li class="request"> <%= link_to 'Sync with LinkedIn', user_omniauth_authorize_path(:linkedin)%> </li>
  </li>
<% end %>
<li> <%= link_to "User Sign out", destroy_user_session_path, :method => :delete %> </li>