config/routes.rb
Wekrut::Application.routes.draw do
  devise_for :views
  devise_for :admins, controllers: {registrations: "admins/registrations", sessions: "admins/sessions"}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", sessions: "users/sessions"}
  resources :users
  resources :admins
  resources :charges
  resources :jobs do
    collection do
      get 'private'
    end
  end

  resources :invitations
  resources :user_profiles

  resources :referrals
  resources :whitelists

  resources :companies do
    member do
      get 'private'
      resources :private_invitations
    end

  end
  resources :accesses

  root "home#index"
  match '/private/:access_token', to: 'home#private', via: 'get'
  match '/send_request', to: 'home#send_request', via: 'post'
  match '/send_company_request', to: 'home#send_company_request', via: 'post'

end

app/views/admins/index.html.erb
<%= render 'layouts/header' %>

<section class="jobs">
<div class="container">

<div>
 <% if admin_signed_in? %>
    Signed in as <%= current_admin.company %>. Not you?
    <%= link_to "Sign out", destroy_admin_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_admin_registration_path, class: "btn btn-default btn-lg" %> <%= link_to "sign in", new_admin_session_path, class: "btn btn-default btn-lg" %>
      </div>
    <% end %>
    <div>
    <%= link_to 'New Job', new_job_path %>
  </div>
<div class="page page-table">

    <div class="panel panel-default">
        <div class="panel-heading"><strong><span class="fa fa-th"></span>
          All Referrals </strong>
    </div>
        <div class="panel-heading">
          <div class="form-inline" role="form">
            <%= search_form_for @search, url: admins_path do |f| %>
              <div class="form-group">
                <%= f.text_field :job_name_or_referral_name_cont, :placeholder => 'Search' %>
              </div>
              <div class="form-group">
                <%= f.submit "Search" %>
              </div>
            <% end %>
          </div>
        </div>



        <table class="table">
  <tr>

    <th><%= sort_link @search, :job_name, "Position" %></th>
    <th><%= sort_link @search, :referral_fee, "Referral Fee" %></th>
    <th><%= sort_link @search, :referral_name, "Candidates" %></th>
    <th><%= sort_link @search, :status, "Status" %></th>
    <th><%= sort_link @search, :created_at, "Date Submitted" %></th>

  </tr>

  <% @sorted_referrals.each do |referral| %>
    <tr>

      <td><%= link_to referral.job.job_name, "/jobs/#{referral.job.id}" %></td>

      <td><%= referral.job.referral_fee %></td>

      <td><%= link_to referral.referral_name, "/referrals/edit/#{referral.id}" %></td>

      <td><%= referral.status.titleize %></td>

      <td><%= time_ago_in_words(referral.updated_at) %></td>

     </tr>

    </tr>
  <% end %>

</table>
</div>
<%= will_paginate @sorted_referrals%>
</div>
</div>
</div>
</section>

app/views/admins/show.html.erb
<%= render 'layouts/header' %>
<section class="jobs">




       
               
 <%= search_form_for @search, url: admin_path(@admin.id) do |f| %>
<div class="container">
  <div class="page page-table">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="form-inline" role="form">
          <div class="form-group">
            <form class="navbar-form navbar-right" action="#" role="search">
              <div class="form-group">    
                <div class="input-group">
                  <input class="form-control" id="q_name_or_job_name_or_city_or_state_cont" name="q[name_or_job_name_or_city_or_state_cont]" placeholder="Search" type="search">
                <span class="input-group-btn">
                  <button type="submit" class="btn"><span class="fa fa-search"></span>
                  </button>
                </span>
                </div>
                </div>           
          </form>
        </div>
               <% end %>
      
           <%= render 'admins/shared/all_referrals'%>
      
       </div>
     </div>
   </div>
 </div>
</div>