config/routes.rb
Wekrut::Application.routes.draw do
  devise_for :views
  devise_for :admins, controllers: {registrations: "admins/registrations", sessions: "admins/sessions"}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", sessions: "users/sessions"}
  resources :users
  resources :admins
  resources :charges
  resources :jobs do
    collection do
      get 'private'
    end
  end

  resources :invitations
  resources :user_profiles

  resources :referrals
  resources :whitelists

  resources :companies do
    member do
      get 'private'
      resources :private_invitations
    end

  end
  resources :accesses

  root "home#index"
  match '/private/:access_token', to: 'home#private', via: 'get'
  match '/send_request', to: 'home#send_request', via: 'post'
  match '/send_company_request', to: 'home#send_company_request', via: 'post'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default("")
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  first_name             :string(255)
#  last_name              :string(255)
#  industry_1             :string(255)
#  industry_2             :string(255)
#  speciality_1           :string(255)
#  speciality_2           :string(255)
#  profile_id             :integer
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  tagline                :string(255)
#  uid                    :string(255)
#  unique_token           :string(255)
#  invited_by_ipf_id      :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :validatable
  SOCIALS = {
    facebook: 'Facebook',
    github: 'Github',
    linkedin: 'Linkedin'
  }
  has_one :inviter_profile, :as => :owner, :dependent => :destroy
  has_one :user_profile, :dependent => :destroy
  belongs_to :whitelist
  has_many :referrals, :dependent => :destroy
  has_many :authorizations, :dependent => :destroy
  has_many :jobs, :through => :referrals
  has_many :accesses
  has_many :companies, :through => :accesses
  validates :first_name, :last_name, :email, presence: true
  validates :email, :uniqueness => { :case_sensitive => false }
  scope :private_company, lambda {|company| joins(:accesses).where('accesses.company_id = ?', company.id)}
  before_create :generate_unique_token
  before_create :generate_inviter_profile
  after_create :update_inviter_profile


  def update_inviter_profile
    inviter = InviterProfile.find(self.invited_by_ipf_id)
    referrals_num = inviter.users_generated
    inviter.update_attribute(:users_generated, referrals_num + 1)
  end

  def generate_unique_token
    self.unique_token = Digest::SHA1.hexdigest([Time.now,rand].join)
  end

  def generate_inviter_profile
    #has_one (create_inviter_profile) vs. has_many (inviter_profile.create)
    self.create_inviter_profile(:unique_token => self.unique_token)
  end

  def has_enterprise? #true to display private
    self.accesses.count > 0 ? true : false
  end

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user, access_token=nil, ipf_id) #default is nil
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where("email = ?", auth["info"]["email"]).first : current_user
      if user.blank?
        user = User.new
        user.create_user(auth, user, ipf_id)
      end
     authorization.user_id = user.id
     authorization.save
   end
    # binding.pry
    authorization.user.check_access_token(access_token, authorization.user_id) unless access_token.nil?
    authorization.user.create_profile(auth, authorization.user)
    authorization.user
  end

  def create_user(auth, user, ipf_id)
    # binding.pry
    user.password = auth["credentials"]["token"]
    #Devise.friendly_token[0,10]
    user.first_name = auth.info.first_name
    user.last_name = auth.info.last_name
    user.email = auth.info.email
    user.invited_by_ipf_id = ipf_id
    user.save
    create_profile(auth, user)
  end

  def create_profile(auth, user)
    profile = UserProfile.find_or_initialize_by(user_id: user.id)
    profile.user_id = user.id
    profile.first_name = auth["info"].fetch("first_name") { nil }
    profile.last_name = auth["info"].fetch("last_name") { nil }
    profile.email = auth["info"].fetch("email") { nil }
    profile.location = auth["info"].fetch("location") { nil }
    profile.headline = auth["info"].fetch("headline") { nil }
    profile.industry = auth["info"].fetch("industry") { nil }
    profile.image = auth["info"].fetch("image") { nil }
    profile.public_profile_url = auth["info"]["urls"].fetch("public_profile") { nil }
    profile.educations = auth["extra"]["raw_info"]["educations"].fetch("values") {nil}
    profile.positions = auth["extra"]["raw_info"]["positions"].fetch("values") {nil}
    all_skills = []
    unless auth["extra"]["raw_info"]["skills"].blank?
      auth["extra"]["raw_info"]["skills"]["values"].each{|value| all_skills << value["skill"].fetch("name") {nil}}
    end

    profile.skills = all_skills
    profile.save!
  end

  def check_access_token(access_token, user_id)
    company_id = Company.find_by_access_token(access_token).id
    #create accesses
    Access.find_or_create_by(user_id: user_id, company_id: company_id, level: 1) unless company_id.nil?
    #2 denotes super user
  end


end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

include UsersHelper

  def create
    email = params[:user][:email].downcase

    # unless Whitelist.exists?(:email => email)
    #   flash[:alert] = "#{email} is currently not on our beta list yet. Sign up #{view_context.link_to('here', root_path)} for our beta version.".html_safe
    #   redirect_to new_user_registration_path
    # else
      resource = build_resource(sign_up_params)
      if resource.save
        yield resource if block_given?
        # if resource.active_for_authentication?
        # end
        if !params[:user][:inviter_email].blank?
          if User.exists?(:email => params[:user][:inviter_email].downcase)
            inviter_email = params[:user][:inviter_email].downcase
            inviter_id = User.find_by_email(inviter_email).id
            if Invitation.exists?(:user_id => inviter_id, :invited_email => email)
              invitation = Invitation.where(:user_id => inviter_id, :invited_email => email)[0]
              invitation.record_success
              InvitationMailer.send_successful_invitation(invitation)
            end
            set_flash_message :notice, :signed_up if is_flashing_format? #flash for successful inviter
          else
            flash[:notice] = "Account successfully created. Please note that we could not find the inviter email in our user database." #flash for bad inviter
          end
        else
          set_flash_message :notice, :signed_up if is_flashing_format? #flash for no inviter
        end
        sign_up(resource_name, resource)
        redirect_to jobs_path
        # else
        #   set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        #   expire_data_after_sign_in!
        #   redirect_to new_user_session_path
        # end
      else
        clean_up_passwords resource
        respond_with resource
      end
    # end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


include UsersHelper

def new
  self.resource = resource_class.new(sign_in_params)
  clean_up_passwords(resource)
  respond_with(resource, serialize_options(resource))
end

def create
  # binding.pry
  access_token = params[:access_token]
  # binding.pry
  resource = warden.authenticate!(auth_options)
  user_id = resource.id
  # binding.pry
  resource.check_access_token(access_token, user_id) unless access_token.nil?
  set_flash_message(:notice, :signed_in) if is_flashing_format?
  sign_in(resource_name, resource)
  yield resource if block_given?
  respond_with resource, location: after_sign_in_path_for(resource)
end

protected


  def after_sign_in_path_for(user)
    jobs_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_session
  before_action :set_user, only: [:show, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :store_location #enables linking back
  before_action :check_main_admin, only: [:index, :new ]

  include ApplicationHelper

  def index
   @users = User.all
  end

  def show
    @user_email = @user.email
# Kaminari.paginate_array(@arr_name).page
    #referrals recevied
    @received_referrals = Referral.received_referrals(@user)
    # .paginate(:page => params[:page]) if !select_received.nil?
    @unreviewed_referrals = Referral.received_referrals(@user).unreviewed
    @unreviewed_count = @unreviewed_referrals.count
    #my referrrals
    @sent_referrals = Referral.sent_referrals(@user)
    # .paginate(:page => params[:page])
    @ask_referrals = Referral.requested_referrals(@user)
    @ask_referrals_count = @ask_referrals.count
    @hav_ref = has_any(@unreviewed_count)
     #
  end

  def destroy
    if @user.destroy
      redirect_to user_omniauth_authorize_path, notice: "Account has been deleted."
    else
      render action: 'edit'
    end
  end

  protected

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :invited_by_ipf_id, :password, :industry_1, :inviter_email, :speciality_1, :referral_id, :profile_id, :tagline)
  end

  def check_session
    if current_user.nil? && current_admin.nil?
      flash[:notice] = "Please sign-in to continue."
      redirect_to user_omniauth_authorize_path
    end
  end

  def correct_user
    user = User.find(params[:id])

    if !current_admin.nil?
      level = Whitelist.find_by_email(current_admin.email).level
    end

    redirect_to new_user_session_path, :error => "You cannot view that account because you're not the correct admin. Please login to the correct account."  unless user == current_user || level == 3
  end

  def check_main_admin
    level = Whitelist.find_by_email(current_admin.email).level
    redirect_to new_admin_session_path, notice: "You are not an approved admin whitelister" if level != 3
  end



end


#only lets main admin see this page
  def check_main_admin
    level = Whitelist.find_by_email(current_admin.email).level
    redirect_to new_admin_session_path, notice: "You are not an approved admin whitelister" if level != 3
  end

app/helpers/users_helper.rb
module UsersHelper
	def industry_choices
		["Financial Services", "Technology", "Fashion", "Non-profit", "Advertising", "Professional Services", "Other"]
	end

	def speciality_choices
		["Marketing", "Technology", "Design", "Administrative", "Recruitment", "Consulting", "Operations", "Finance", "Business Development", "Account Management", "Other"]
	end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_path(id)
    user_path(id)
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
  end

end

app/views/users/shared/_ask_referrals.html.erb
    <div class="page page-table">
      <div class="panel panel-default">
      <div class="panel-heading"><strong><span class="fa fa-th"></span>
        Requested Referrals</strong>
      </div>
        <table class="table">
          <thead>
          <tr>
            <th>Company</th>
            <th>Job</th>
            <th>Status</th>
            <th>Date Requested</th>
            <th>Requester</th>
          </tr>
          </thead>
          <tbody class="page">
            <% @ask_referrals.each do |referral| %>
          <tr class="received">
            <td><%= link_to referral.job.name, job_path(referral.job.id), class: "#{referral.is_interested}-stat" %></td>
            <td><%= link_to referral.job.job_name, job_path(referral.job.id), class: "#{referral.is_interested}-stat" %></td>
            <!-- need to change the way class is entered -->
            <td class="#{referral.is_interested}-stat"><%= referral.status.titleize %></td>
            <td class="#{referral.is_interested}-stat"><%= time_ago_in_words(referral.created_at) %></td>
            <td class="#{referral.is_interested}-stat"><%="#{referral.user.first_name.titleize} #{referral.user.last_name.titleize}"%></td>
            <td><%= link_to "Review Job", job_path(referral.job.id), class: "btn btn-primary"%>
            <%= link_to "Delete Request", referral, :method => :delete, class: "btn btn-primary"%>
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

app/views/users/shared/_links.erb
<table>
	<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign Up with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

</table>

app/views/users/shared/_received_referrals.html.erb
<div class="page page-table">
      <div class="panel panel-default">
      <div class="panel-heading"><strong><span class="fa fa-th"></span>
        Received Referrals</strong>

      </div>
        <table class="table">
          <tr>
            <th>Company</th>
            <th>Job</th>
            <th>Status</th>
            <th>Last Update</th>
            <th>Interested?</th>
          </tr>
          <tbody class="page">
            <% @received_referrals.each do |referral| %>
          <tr class="received">
            <td><%= link_to referral.job.name, edit_referral_path(referral.id), class: "#{referral.is_interested}-stat" %></td>
            <td><%= link_to referral.job.job_name, edit_referral_path(referral.id), class: "#{referral.is_interested}-stat" %></td>
            <!-- need to change the way class is entered -->
            <td class="#{referral.is_interested}-stat"><%= referral.status.titleize %></td>
            <td class="#{referral.is_interested}-stat"><%= time_ago_in_words(referral.updated_at) %></td>
            <td><%= link_to "#{translate_boolean(referral.is_interested)}", edit_referral_path(referral.id), class: "#{referral.is_interested}-stat" %></td>
            <td><%= link_to "Update", edit_referral_path(referral.id), class: "btn btn-primary"%> </td>
          </tr>
          <% end %>


          </tbody>
        </table>
      </div>
    </div>

app/views/users/shared/_sent_referrals.html.erb
<div class="page page-table">
  <div class="panel panel-default">
  <div class="panel-heading"><strong><span class="fa fa-th"></span>

  <strong> Sent Referrals</strong>

  </div>
    <table class="table">
      <thead>
      <tr>
        <th>Company</th>
        <th>Job</th>
        <th>Candidate</th>
        <th>Referral Fee</th>
        <th>Last Updated</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <% @sent_referrals.each do |referral| %>
      <tr>
        <td><%= referral.job.name %></td>
        <td><%= referral.job.job_name %></td>

        <td><%= referral.referral_name %></td>
        <!-- need to change the way class is entered -->
        <td class="#{referral.is_interested}-stat"><%= number_to_currency(calculate_fee(referral.job.referral_fee), precision: 0)  %></td>
        <td class="#{referral.is_interested}-stat"><%= time_ago_in_words(referral.updated_at) %></td>
        <td><%= referral.status %></td>

      </tr>
      <%end%>
      </tbody>
    </table>
  </div>
</div>