config/routes.rb
Wekrut::Application.routes.draw do
  devise_for :views
  devise_for :admins, controllers: {registrations: "admins/registrations", sessions: "admins/sessions"}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", sessions: "users/sessions"}
  resources :users
  resources :admins
  resources :charges
  resources :jobs do
    collection do
      get 'private'
    end
  end

  resources :invitations
  resources :user_profiles

  resources :referrals
  resources :whitelists

  resources :companies do
    member do
      get 'private'
      resources :private_invitations
    end

  end
  resources :accesses

  root "home#index"
  match '/private/:access_token', to: 'home#private', via: 'get'
  match '/send_request', to: 'home#send_request', via: 'post'
  match '/send_company_request', to: 'home#send_company_request', via: 'post'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @company = Company.new
  end

  def private
    @access_token = params[:access_token]
    @company = Company.find_by_access_token(@access_token)
    redirect_to root_path, notice: 'Private site does not exists. Please check your URL or contact info@wekrut.com' if @company.nil?
    #flash[:error] not working?
  end

  #beta request email
  def send_request
    email = params[:email]
    linked_in = params[:linked_in]

    if [email, linked_in].select{|x| x==""}.empty?
      #binding.pry
      BetaMailer.deliver_beta_request(email,linked_in)
      redirect_to root_path, notice: 'Your request has been sent!'
    else
      redirect_to root_path, error: 'Request was not sent because there were missing fields. Please fill in all fields'
    end
  end

#company request email
    def send_company_request
    user_name = params[:user_name]
    user_email = params[:user_email]
    recruiter_name = params[:recruiter_name]
    recruiter_email = params[:recruiter_email]
    company = params[:company]

    if [user_name, user_email, recruiter_name, recruiter_email, company].select{|x| x==""}.empty?
      #binding.pry
      CompanyMailer.deliver_company_request(user_name, user_email, recruiter_name, recruiter_email, company)
      #binding.pry
      redirect_to root_path, notice: 'Your request has been sent!'
    else
      redirect_to root_path, error: 'Request was not sent because there were missing fields. Please fill in all fields'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_beta_form.html.erb
<%= content_tag(:div, flash.now[:notice], :id => "flash_notice") if flash.now[:notice] %>

<h2>
  Beta Sign Up:
</h2>

<%= content_tag(:div, flash.now[:error], :id => "flash_error") if flash.now[:error] %>

<%= form_tag(send_request_path) do %>
  <div class="form-group">
      <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Email Address' %>
  </div>
  <div class="form-group">
      <%= text_field_tag 'linked_in', nil, class: 'form-control', placeholder: 'LinkedIn URL' %>
  </div>
 <%= submit_tag nil, class: 'btn btn-default btn-about' %>

<% end %>

app/views/home/_company_form.html.erb
<%= content_tag(:div, flash.now[:notice], :id => "flash_notice") if flash.now[:notice] %>

<h2>
  Refer your company to join. When they place their first candidate, you get $100!
</h2>

<%= content_tag(:div, flash.now[:error], :id => "flash_error") if flash.now[:error] %>

<%= form_tag(send_company_request_path) do %>
 <div class="form-group">
      <%= text_field_tag 'user_name', nil, class: 'form-control', placeholder: 'Your Name' %>
  </div>
  <div class="form-group">
      <%= email_field_tag 'user_email', nil, class: 'form-control', placeholder: 'Your Email Address' %>
  </div>
   <div class="form-group">
      <%= text_field_tag 'recruiter_name', nil, class: 'form-control', placeholder: 'Talent Contact Name' %>
  </div>
  <div class="form-group">
      <%= email_field_tag 'recruiter_email', nil, class: 'form-control', placeholder: 'Talent Contact Email' %>
  </div>
  <div class="form-group">
      <%= text_field_tag 'company', nil, class: 'form-control', placeholder: 'Company Name' %>
  </div>
 <%= submit_tag nil, class: 'btn btn-default btn-about' %>

<% end %>

app/views/home/enterprise.html.erb
<nav class="navbar-home navbar-fixed-top" role="navigation">

 <div class="container">
   <div class="navbar-header page-scroll">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
       <i class="fa fa-bars"></i>
     </button>
     <a class="navbar-brand" href="http://www.wekrut.com">
       <span class="light">&nbsp&nbsp&nbspWe</span>Krüt
     </a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
     <ul class="nav navbar-nav">
       <!-- Hidden li included to remove active class from about link when scrolled up past about section -->

     </li>
     <li class="page-scroll">
       <a href="#about">About</a>
     </li>
     <li class="page-scroll">
      <%= link_to 'Jobs', jobs_path %>
    </li>
    <li class="page-scroll">
                  <% if !user_signed_in? && !admin_signed_in? %>
                    <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Login<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                       <li><%= link_to "User", new_user_session_path(:access_token => @access_token) %></li>
                       <li><%= link_to "Recruiter", new_admin_session_path %></li>
                      </ul>
                    </li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        ACCOUNT
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-menu">
                          <% if user_signed_in? %>
                            <li> <%= link_to 'My Referrals', user_path(current_user.id)%> </li>
                            <li> <%= link_to "User Sign out", destroy_user_session_path, :method => :delete %> </li>
                          <% else admin_signed_in? %>
                            <li> <%= link_to 'My Referrals', admin_path(current_admin.id) %> </li>
                            <li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>
                          <% end %>
                        </li>
                      </ul>
                    </li>
                <% end %>
              </li>
 </div>
</div>
</nav>
  <section class="intro">

    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2 class="brand-heading">Get Paid<br>For<br> Referrals</h2>

                    <!-- Button trigger modal -->

<%= link_to 'CONNECT WITH LINKEDIN', user_omniauth_authorize_path(:linkedin, :access_token => @access_token),class: "btn-linkedin btn-lg" %>
<!-- Testing -->
<%= link_to @company.name, user_omniauth_authorize_path(:linkedin, :access_token => @access_token),class: "btn-linkedin btn-lg" %>
<div>You're on <%=@company.name%> Invitation Page! Please sign up/in here! </div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'home/beta_form' %>
      </div>
     </div>
    </div>
  </div>
</div>
<br>
<br>

<button class="btn btn-default btn-about btn-lg" data-toggle="modal" data-target="#myModal2">
  &nbsp&nbspInvite Your Company&nbsp&nbsp

</button>
 <%= content_tag(:div, flash.now[:notice], :id => "flash_notice") if flash.now[:notice] %>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'home/company_form' %>
      </div>
     </div>
    </div>
  </div>
</div>

                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                </div>
            </div>
        </div>

    </div>
  </section>
  <section id="about">

    <div class="container about-section text-center">
      <div class="col-md-4 ">
        <div class="clearfix"></div>
        <%= image_tag "imac_jobs.png", :class => "img-responsive center-block" %>
        <h3>Search Through<br>Great jobs</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
        <%= image_tag "triangle.png", :class => "img-responsive center-block" %>
        <h3>Refer Your<br>Network</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
       <%= image_tag "heartdollar.png", :class => "img-responsive center-block" %>
       <h3>They Get Hired<br>You Get Paid</h3>
      </div>
    </div>
  </section>


  <div class="banner">

    <div class="container">
     <div class="span6">
        <div class="flex-video widescreen" style="margin: 0 auto;text-align:center;">
        <iframe src="//www.youtube.com/embed/l9FHhl4hg7k?autoplay=0&controls=2&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
        </div>

      </div>


    </div>

  </div>
</div>



  <%= render 'layouts/footer' %>

app/views/home/index.html.erb
<nav class="navbar-home navbar-fixed-top" role="navigation">

 <div class="container">
   <div class="navbar-header page-scroll">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
       <i class="fa fa-bars"></i>
     </button>
     <a class="navbar-brand" href="http://www.wekrut.com">
       <span class="light">&nbsp&nbsp&nbspWe</span>Krüt
     </a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
     <ul class="nav navbar-nav">
       <!-- Hidden li included to remove active class from about link when scrolled up past about section -->

     </li>
     <li class="page-scroll">
       <a href="#about">About</a>
     </li>
     <li class="page-scroll">
      <%= link_to 'Jobs', jobs_path %>
    </li>
    <li class="page-scroll">
                  <% if !user_signed_in? && !admin_signed_in? %>
                    <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Login<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                       <li><%= link_to "User", new_user_session_path %></li>
                       <li><%= link_to "Recruiter", new_admin_session_path %></li>
                      </ul>
                    </li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        ACCOUNT
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-menu">
                          <% if user_signed_in? %>
                            <li> <%= link_to 'My Referrals', user_path(current_user.id)%> </li>
                            <li> <%= link_to "User Sign out", destroy_user_session_path, :method => :delete %> </li>
                          <% else admin_signed_in? %>
                            <li> <%= link_to 'My Referrals', admin_path(current_admin.id) %> </li>
                            <li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>
                          <% end %>
                        </li>
                      </ul>
                    </li>
                <% end %>
              </li>
 </div>
</div>
</nav>
  <section class="intro">

    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2 class="brand-heading">Get Paid<br>For<br> Referrals</h2>
<%= content_tag(:div, flash.now[:error], :id => "flash_error") if flash.now[:error] %>
                    <!-- Button trigger modal -->

<%= link_to 'CONNECT WITH LINKEDIN', user_omniauth_authorize_path(:linkedin),class: "btn-linkedin btn-lg" %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'home/beta_form' %>
      </div>
     </div>
    </div>
  </div>
</div>
<br>
<br>

<button class="btn btn-default btn-about btn-lg" data-toggle="modal" data-target="#myModal2">
  &nbsp&nbspInvite Your Company&nbsp&nbsp

</button>
  <%= content_tag(:div, flash.now[:notice], :id => "flash_notice") if flash.now[:notice] %>
<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'companies/shared/form' %>
      </div>
     </div>
    </div>
  </div>
</div>

                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                </div>
            </div>
        </div>

    </div>
  </section>
  <section id="about">

    <div class="container about-section text-center">
      <div class="col-md-4 ">
        <div class="clearfix"></div>
        <%= image_tag "imac_jobs.png", :class => "img-responsive center-block" %>
        <h3>Search Through<br>Great jobs</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
        <%= image_tag "triangle.png", :class => "img-responsive center-block" %>
        <h3>Refer Your<br>Network</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
       <%= image_tag "heartdollar.png", :class => "img-responsive center-block" %>
       <h3>They Get Hired<br>You Get Paid</h3>
      </div>
    </div>
  </section>


  <div class="banner">

    <div class="container">
     <div class="span6">
        <div class="flex-video widescreen" style="margin: 0 auto;text-align:center;">
        <iframe src="//www.youtube.com/embed/l9FHhl4hg7k?autoplay=0&controls=2&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
        </div>

      </div>


    </div>

  </div>
</div>



  <%= render 'layouts/footer' %>

app/views/home/private.html.erb
<nav class="navbar-home navbar-fixed-top" role="navigation">

 <div class="container">
   <div class="navbar-header page-scroll">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
       <i class="fa fa-bars"></i>
     </button>
     <a class="navbar-brand" href="http://www.wekrut.com">
       <span class="light">&nbsp&nbsp&nbspWe</span>Krüt
     </a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
     <ul class="nav navbar-nav">
       <!-- Hidden li included to remove active class from about link when scrolled up past about section -->

     </li>
     <li class="page-scroll">
       <a href="#about">About</a>
     </li>
    <li class="page-scroll">
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Jobs<b class="caret"></b></a>
        <ul class="dropdown-menu">
         <li><%= link_to "Jobs", jobs_path %></li>
         <li><%= link_to "Private Jobs", private_jobs_path %></li>
        </ul>
      </li>
    </li>
    <li class="page-scroll">
                  <% if !user_signed_in? && !admin_signed_in? %>
                    <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Login<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                       <li><%= link_to "User", new_user_session_path(:access_token => @access_token) %></li>
                       <li><%= link_to "Recruiter", new_admin_session_path %></li>
                      </ul>
                    </li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        ACCOUNT
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-menu">
                          <% if user_signed_in? %>
                            <li> <%= link_to 'My Referrals', user_path(current_user.id)%> </li>
                            <li> <%= link_to "User Sign out", destroy_user_session_path, :method => :delete %> </li>
                          <% else admin_signed_in? %>
                            <li> <%= link_to 'My Referrals', admin_path(current_admin.id) %> </li>
                            <li> <%= link_to "Recruiter Sign out", destroy_admin_session_path, :method => :delete %> </li>
                          <% end %>
                        </li>
                      </ul>
                    </li>
                <% end %>
              </li>
 </div>
</div>
</nav>
  <section class="intro">

    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2 class="brand-heading">Get Paid<br>For<br> Referrals</h2>

                    <!-- Button trigger modal -->

<%= link_to 'CONNECT WITH LINKEDIN', user_omniauth_authorize_path(:linkedin, :access_token => @access_token),class: "btn-linkedin btn-lg" %>
<!-- Testing -->
<%= link_to @company.name, user_omniauth_authorize_path(:linkedin, :access_token => @access_token),class: "btn-linkedin btn-lg" %>
<div>You're on <%=@company.name%> Invitation Page! Please sign up/in here! </div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'home/beta_form' %>
      </div>
     </div>
    </div>
  </div>
</div>
<br>
<br>

<button class="btn btn-default btn-about btn-lg" data-toggle="modal" data-target="#myModal2">
  &nbsp&nbspInvite Your Company&nbsp&nbsp

</button>
 <%= content_tag(:div, flash.now[:notice], :id => "flash_notice") if flash.now[:notice] %>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="container" style="margin-top:160px">



  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>

      <div class="modal-body">
        <%= render 'home/company_form' %>
      </div>
     </div>
    </div>
  </div>
</div>

                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                </div>
            </div>
        </div>

    </div>
  </section>
  <section id="about">

    <div class="container about-section text-center">
      <div class="col-md-4 ">
        <div class="clearfix"></div>
        <%= image_tag "imac_jobs.png", :class => "img-responsive center-block" %>
        <h3>Search Through<br>Great jobs</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
        <%= image_tag "triangle.png", :class => "img-responsive center-block" %>
        <h3>Refer Your<br>Network</h3>
      </div>
      <div class="col-md-4">

        <div class="clearfix"></div>
       <%= image_tag "heartdollar.png", :class => "img-responsive center-block" %>
       <h3>They Get Hired<br>You Get Paid</h3>
      </div>
    </div>
  </section>


  <div class="banner">

    <div class="container">
     <div class="span6">
        <div class="flex-video widescreen" style="margin: 0 auto;text-align:center;">
        <iframe src="//www.youtube.com/embed/l9FHhl4hg7k?autoplay=0&controls=2&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
        </div>

      </div>


    </div>

  </div>
</div>



  <%= render 'layouts/footer' %>